### ISSUE TITLE
Multiple zip files are filling the tmp folder

### ISSUE THREAD

**Issue by kyotocanuck** [danmunn/redmine_dmsf#1017]
Since upgrading to 1.6.2, multiple zip files are flooding the tmp folder. The contents are files from the dmsf folder and are random in nature. The name of the files is yymmddhhmm_dmsf_zip.zip. I do not even know where to begin to debug this. Version is 1.6.2 running on redmine 3.4.6

**Comment by picman** [comment]
These files are created when multiple documents are downloaded or sent by email.
_app/controllers/dmsf_controller.rb_ file _email_entries_, _download_entries_ methods

**Comment by kyotocanuck** [comment]
Thank you for the reply. This is good. Is there a function to clear these files? Or should I just use crontab?

________________________________

**Comment by picman** [comment]
I'll try to fix it in the code. Meanwhile, you an delete them from a cron job.

**Comment by picman** [comment]
The problem has been fixed by using standard Ruby [Tempfile](https://ruby-doc.org/stdlib-2.5.3/libdoc/tempfile/rdoc/Tempfile.html) class. The files can't be deleted immediately because when they are being downloaded, they are handed over to the underlying web server and processed independently. The _Tempfile_ class guarantees that they are sooner or later deleted.
