### ISSUE TITLE
Status 404 after moving the folder to another project

### ISSUE THREAD

**Issue by dinya** [danmunn/redmine_dmsf#1106]
Element | In the source place | After moving the folder to another project (from ``test2`` to ``00 test``) | Notes
--------|-----------------|------------------------------------------------------------------------------|------
Folder | ![dir0](https://user-images.githubusercontent.com/2182222/79187443-ae3fba80-7e35-11ea-96ac-ef1d390ae961.png) | ![dir1](https://user-images.githubusercontent.com/2182222/79187444-aed85100-7e35-11ea-95de-28d889790d1c.png) | Before moving to another project dmsf shows ``[1]`` element , but after moving --- ``[0]``.
Folder content | ![contents0](https://user-images.githubusercontent.com/2182222/79187429-a08a3500-7e35-11ea-8c17-ca033a496e8c.png) | ![content1](https://user-images.githubusercontent.com/2182222/79187427-9f590800-7e35-11ea-86c7-0e893f81ee1a.png) | Folders content is rendered as the same.
WebDAV (under Firefox) | ![webdav0](https://user-images.githubusercontent.com/2182222/79187445-aed85100-7e35-11ea-88e6-4a409c2e6ace.png) | ![webdav1](https://user-images.githubusercontent.com/2182222/79187446-af70e780-7e35-11ea-8604-8a259e6062f6.png) | After moving file name is rendered, but the click returns ``404``.

The environment is old enough (not tested on modern redmine+dmsf):

```
Environment:
  Redmine version                3.4.11.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.11.1
...
Redmine plugins:
    ...
    redmine_dmsf                   1.6.2
    ...
```

**Comment by picman** [comment]
Fixed.

**Comment by dinya** [comment]
@picman 

OK, but how to move (now) all previously "incorrectly" moved folders correctly . Or does the commit fixes this?

**Comment by picman** [comment]
No, the fix will be available in the next release only. The problem is that when a folder is moved from project A to project B, all the sub-folders, files and links remain assigned to project A. A workaround is:
1) Upgrade to DMSF 2.4.3
or 
1) Do not copy folders between projects.
2) Fix project_id column in dmsf_folders, dmsf_files and dmsf_links tables of your database by items which were moved and have wrong project_id.

BTW, it's quite a big bug, which is seems to be there from the begining. Thank you for reporting it.

**Comment by dinya** [comment]
I'm sorry, I may have misunderstood. Will "1. Updating to DMSF 2.4.3" automatically correct previously incorrectly placed objects in the plugin upgrade procedure? Thus the item "3. Fix <..>" (manually) will not be needed.
