### ISSUE TITLE
Vim edit through webdav causes lose of all file versions besides last.

### ISSUE THREAD

**Issue by surick1** [danmunn/redmine_dmsf#1413]
Hello, thanks for your plugin.

When I try to edit file with vim editor (both in ubuntu and mac) through webdav after save all history (versions of file) lost (only last version remains).

Tested on "clean" redmine version 5.0.3 and redmine_dmsf version 3.0.7.

Thanks,
Suren.

**Comment by picman** [comment]
The cause of the problem seems to be in a "non-standard" behavior of vi editor. I've added some logging to monitor WebDAV requests coming from the editor. The procedure was open a document, make a small change, save and close. In the log I see:

```
I, [2022-12-16T08:44:39.223853 #164075]  INFO -- : >>> LOCK /c1/.test.txt.swp
I, [2022-12-16T08:44:39.353871 #164075]  INFO -- : >>> LOCK /c1/.test.txt.swx
I, [2022-12-16T08:44:39.518504 #164075]  INFO -- : >>> DELETE /c1/.test.txt.swx
I, [2022-12-16T08:44:41.349465 #164075]  INFO -- : >>> DELETE /c1/.test.txt.swp
I, [2022-12-16T08:44:42.225622 #164075]  INFO -- : >>> LOCK /c1/.test.txt.swp
I, [2022-12-16T08:44:47.027150 #164075]  INFO -- : >>> LOCK /c1/4913
I, [2022-12-16T08:44:47.314369 #164075]  INFO -- : >>> DELETE /c1/4913
I, [2022-12-16T08:44:48.786317 #164075]  INFO -- : >>> MOVE /c1/test.txt to /c1/test.txt~    <<<
I, [2022-12-16T08:44:48.985238 #164075]  INFO -- : >>> LOCK /c1/test.txt~
I, [2022-12-16T08:44:49.109444 #164075]  INFO -- : >>> DELETE /c1/test.txt
I, [2022-12-16T08:44:49.186871 #164075]  INFO -- : >>> LOCK /c1/test.txt
I, [2022-12-16T08:44:49.382623 #164075]  INFO -- : >>> DELETE /c1/test.txt~    <<<
I, [2022-12-16T08:44:50.203010 #164075]  INFO -- : >>> DELETE /c1/.test.txt.swp
I, [2022-12-16T08:45:01.678716 #164075]  INFO -- : >>> PUT /c1/test.txt    <<<
I, [2022-12-16T08:45:01.804927 #164075]  INFO -- : >>> UNLOCK /c1/test.txt

```
Critical requests marked with '<<<'. In general, the editor moves the edited file to a temporary file with ~ extension, then deletes it and uploads a new file. That is the reason why the original file including it's history is deleted and after saving you can see a completely new document with different ID while the original is in the trash bin.

Question is, what to do with that.

BTW, thank to your report I found a bug in implementation of LOCK request and consequently fixed editing in Gedit and LibreOffice.

**Comment by surick1** [comment]
Thanks, for detailed explanation of the issue.

**Comment by surick1** [comment]
Hello, the issue is still actual.

When I try to edit file with vim editor (both in ubuntu and mac) through webdav after save all history (versions of file) lost (only last version remains).

Tested on "clean" redmine version 5.0.4 and redmine_dmsf version 3.0.8.

Thanks,
Suren.

**Comment by picman** [comment]
Maybe, reread my last comment....
