### ISSUE TITLE
Upload file with '[' / ']' in the name

### ISSUE THREAD

**Issue by ovhk** [danmunn/redmine_dmsf#1416]
Cannot upload a file with '[' or ']' in the name (ex. "ABCDEF [A] [ ].pdf")

**Comment by picman** [comment]
That is a feature. Square brackets are used to distinguish between folders and sub-projects . It wouldn't be a problem in GUI but if you access DMS via WebDAV, than square brackets in the path would be mistakenly considered as sub-projects instead of file name. From this reason, square brackets are not allowed in file names.
