### ISSUE TITLE
DMS configuration setting for Libreoffice was made with an error

### ISSUE THREAD

**Issue by dskibarko** [danmunn/redmine_dmsf#1535]
Used Bitnami 5.0.3. and was secessfully upgrade to DMS version 3.1.8
After that, I suppose, the DMS configuration setting for Libreoffice was made with an error in the plugin configuration

**[408ac8e5-c0c4-4d57-881a-39cbfc03f1a0] LibreOffice's command line binary '"C:\Program Files\LibreOffice\program\soffice.exe"' not available**

As a result, it is impossible to enter the settings page to fix (return) and it is impossible to download files.
Questions:
1. In this case, how do I return the setting to its original state?
2. Is it possible to detail info how to fill in the field so that DMS knows about Libreoffice and everything works?

Thanks!

**Comment by picman** [comment]
I've just tested it and it works fine, I'd say. Concerning settings, I can open it independently on the value set in **Libreoffice binary**:
![image](https://github.com/user-attachments/assets/3655cce8-214e-41f7-82a3-86b4c888679d)
And, if the set binary is not found, it simply offers the file for downloading instead of inline viewing. In the log you can see a warning then: 
`WARN -- : LibreOffice's command line binary 'C:\Program Files\LibreOffice\program\soffice.ex' not available`

Maybe post a bit bigger chunk of _production.log_ file to see probably another error preventing settings from opening. And the same for an unsuccessful download.
As a workaround you can modify the settings directly in the database, table _settings_.

**Comment by picman** [comment]
No feedback => closing.
