### ISSUE TITLE
WebDav: Excel files fail to open

### ISSUE THREAD

**Issue by dvader** [danmunn/redmine_dmsf#185]
Opening an Excel file through a WebDav mounted drive in Windows fails.

![image](https://f.cloud.github.com/assets/2127127/1665109/03821ccc-5c32-11e3-8477-ef2129b945ce.png)
![image](https://f.cloud.github.com/assets/2127127/1665113/0e3eab08-5c32-11e3-9e85-8d850d18c407.png)

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.9.3 (i386-mingw32)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         Mysql2
Redmine plugins:
  redmine_ckeditor                         1.0.12
  redmine_dmsf                             1.4.6 stable

**Comment by ocanam** [comment]
Even if it's not exactly linked to the bug initially described, I can relate my experience of DMSF's WebDAV with Office 2013, maybe it can give some clues:
- Due to the temporary files created when a document is opened, Office just kill the versioning of DMSF. With Word 2013, I ends with a one-revision old document added in DMSF with the ~temporary name. The original file which could have already many revision was deleted from DMSF (still here on the hdd).
- After closing the document, and even Word, it was still locked in DMSF and must be unlocked manually.

It's all side effects of the way how Office save the files.

**Comment by xJom** [comment]
I can't even open the Office 2013 files from the WebDAV mounted area. Is there a work-around for this problem?

**Comment by xJom** [comment]
I found the work-around myself - https://support.microsoft.com/en-us/kb/2123563

**Comment by picman** [comment]
I believe that it works quite stable with the latest Microsoft Office and DMSF, so I'd close this issue. All in all LibreOffice is recommended.
