### ISSUE TITLE
Webdav not open

### ISSUE THREAD

**Issue by DenKey** [danmunn/redmine_dmsf#541]
Hi.Try open webdav but get raw html, i check my access and all normally.

- DMSF                    1.5.6
- Redmine version    3.2.0.stable
- Ruby version          2.2.1-p85 (2015-02-26) [x86_64-linux]
- Rails version          4.2.5

P.S. I looking how move file from folder to folder but can't understand how can do it,  for this purpose opened webdav and get this error may be you say me how ? 

![dmsf](https://cloud.githubusercontent.com/assets/9421428/16521876/9cbe9acc-3fa2-11e6-9bcc-ceda7c423e83.png)

**Comment by picman** [comment]
There are two options to move files:
1) Go to the document's details and click Copy/Move from the top menu.
2) Use a WebDAV client. Connect to the project and using drag&drop move the file.

I've no idea why your browser display HTML as the source code instead of displaying the HTML result, but WebDAV in HTML browser is certainly read-only.

**Comment by DenKey** [comment]
I can't see this  buttons Copy/Move while not including this  CSS file  

```
.file .buttons>a img {
    display: inline;
}

.file .buttons>a[data-method="delete"]:before {
    display:none;
}
```

I use theme **PurpleMine2** maybe these we have some incompatibility

**Comment by pacoaguayo** [comment]
Hi DenKey, 

I solved it with this change on httpd.conf file, inside of:  /etc/httpd/conf/httpd.conf

Where:  DefaultType text/plain
It's necessary:  DefaultType text/html
And then, restart Apache. 

That's all.
Regards!
