### ISSUE TITLE
Feature Request: Document Location - Folder Structure

### ISSUE THREAD

**Issue by ABaumgaertner** [danmunn/redmine_dmsf#543]
when large number of files (10.000+) are stored in a single directory, all file systems become inefficient.

please adopt the DMSF document storage on the file system, based on e.g. the upload date:
current "DMSF document location"/project1/DTTM_Filename
improved "DMSF document location"/project1/2016/07/14/DTTM_Filename
it would be important to create subdirectories for years, months and days to keep the main directory as clean as possible.

The external representation via redmine / webdav would be unaffected.

Please provide a migration option for existing documents.

Path Length: this would add 11 characters to the path length which can be a limiting factor on some OS

Thanks for your work - DMSF is so great, that you want to store that many files with it :+1:

**Comment by picman** [comment]
A good point. However, I'd suggest to omit the project name from the path and to organize documents the same way as attachments. I mean 2017/03/doc1.odt,... From the application point of view it doesn't mater where the files are stored and the folder structure based on dates reduces noticeable server resources while e.g. scanning for viruses or indexing for a full text-search as it's enough to scan only the folder according to the current date.

**Comment by carlolars** [comment]
👍 
One more thing, when omitting the project names in the path then moving files between projects does not have to physically move the files on disk anymore.

**Comment by picman** [comment]
So the new file system structure corresponds with attachments and is as follows:
{year}/{month}
A critical point, I think, might be in the migration where all the existing documents are moved to their new location.
If anyone might have an opportunity to test it, please do that and provide me a feedback.

**Comment by picman** [comment]
There is one big problem remaining: If a document has got more revisions which refer to the same physical file, the first revision might be in 2017/06 while another in 2017/07. It would lead to 404 - not found when accessing the second revision.

**Comment by picman** [comment]
Fixed.

**Comment by jmfarina** [comment]
Hello,
We're using version devel-1.6.0 and it seems that the migration of the files to the new structure isn't working.
I've run
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
and while the DB seems to be expecting the new structure, files remain under the old one. I couldn't find a log to check if it reported any problems.

And just to play devil's advocate, I think that perhaps keeping the folder structures organized by project (folders with dates could go inside those) might be easier in for maintainance/migration. I don't have a good use case in mind right now, I'd just argue that it would be easier to spot a certain file, For instance, in the not-so-common case I'm facing right now, I would have had to know the date I've uploaded a file in order to find it in the filesystem (I know it's not much of a good point, just another point of view).
Also, I'm not sure if I understood the comment about moving the files, but just in case I wanted to point out that in the event of needing to move files from one project to the other, it shouldn't be a costly operation since the files aren't actually moved around (at least in UNIX, as far as I know).
