### ISSUE TITLE
Documents ID easy access

### ISSUE THREAD

**Issue by cartsofware** [danmunn/redmine_dmsf#555]
Hi,
it would be very handy if you could add a column (or something similar) with the document's ID for easy access to it! so 'unskilled' users can reference document on issue or wiki more easily

Kind regards

**Comment by picman** [comment]
You can see the document ID in the document details or in the footer of the browser when you point on the document. I don't consider as a good idea to add another column with ID.

**Comment by mmundi72** [comment]
I disagree to this: in standard redmine the ticket list always shows the ticket number (unless I hide it). Clicking on the ticket number shows the details page.

To follow this standard I would expect to have the document / folder ID as well in the list. This could serve the following purpose:
- Click on the number to show the details page of the document (same behaviour as for tickets; the detail icon is quite cumbersome)
- Easy access to the number for referencing purposes (with my collegues I often tell them just the ticket number, why not for documents?)

Please consider this once more. Maybe the additional column can be selected in the settings of the module (well for me the column workflow is uselesse - i would rather have the ID column instead of the workflow column).

Best regards.

**Comment by picman** [comment]
Okay. Maybe you're right. I'll maake it optional.

**Comment by picman** [comment]
You can select ID column to be visible in the plugin's settings.
