### ISSUE TITLE
When saving a file use first lines in document for description

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#636]
When a file is created via WebDAV then the description field is always empty. It would be nice if a few of the first lines in the document were used for the description when saving a document, and updated every time the document is saved again.

But if someone has written a real description then that description should be used, so the auto-description must be tagged somehow.

**Comment by picman** [comment]
Have you an idea how to easily get a few first lines from a document? e.g PDF, ODT,...

**Comment by carlolars** [comment]
Probably not easy... But if you use full-text search you install the tools that are needed.

**Comment by carlolars** [comment]
Come to think of it, there is no reason this feature should be used only when saving via WebDAV. Updated title.

**Comment by picman** [comment]
Reasons why to not implement it:
1. The full-text search is optional and includes installation of tenth of packages for converting different document formats to plain text.
2. The full-text search use an index that is created as a parallel job, because converting a 1GB PDF document to plain text can take tenth of seconds.

**Comment by carlolars** [comment]
Reason 2 kills this feature... But it would have been cool ;)

**Comment by picman** [comment]
Closed. Sorry.
