### ISSUE TITLE
Missing date picker when creating new file

### ISSUE THREAD

**Issue by rems4e** [danmunn/redmine_dmsf#652]
Context:
* Redmine 3.3.2
* DMSF 1.5.8
* Custom date field added with Redmine to DMSF

When I upload a new document, there is no date picker, only a text field (checked on Firefox Linux/Mac, Chromium and Safari), whereas on adding  a new revision of a document, the date picker is present.

I tracked this down to the JavaScript not being able to find the date field and adding the date picker to the field.
The reason JS does not appear to be able to select these fields (through an expression like this: `$('#commited_files[0][dmsf_file_revision]_custom_field_values_26')` is because of the brackets.

If I remove these brackets, I am able to correctly select the entities, and I suppose the date pickers would appear, and the revision creation's fields do not have brackets in their IDs.

**Comment by picman** [comment]
You're right, jQuery is not able to select tags with '[]' in their IDs. A solution would be to remove square brackets from the ID but we can't do that because when we're uploading multiple documents we need their parameters in an array. Unfortunately, the redmine method _custom_field_tag_with_label_ doesn't support :id as an option.
A better approach would be to sanitize object name in Redmine application_helper.rb:

```ruby
 def calendar_for(field_id)
    include_calendar_headers_tags
1175 -    javascript_tag("$(function() { $('##{field_id}').addClass('date').datepickerFallback(datepickerOptions); });")
1175 +    javascript_tag("$(function() { $('##{field_id.gsub!('\[', '\\\\[').gsub!('\]', '\\\\]') }').addClass('date').datepickerFallback(datepickerOptions); });")
  end
```

But, I don't know how to do that.

**Comment by picman** [comment]
Finally solved by patching the application helper and substituting square brackets there.
