### ISSUE TITLE
Webdav: moving a folder that contains locked files/folders should not be allowed

### ISSUE THREAD

**Issue by carlolars** [danmunn/redmine_dmsf#672]
The response should be a Multi-Status that contains the 423 Locked status for (all) locked files in the folder.

**Comment by picman** [comment]
Can we close it?

**Comment by carlolars** [comment]
I have not solved this and will not be able to do so in a near future, better move this to 1.6.

**Comment by picman** [comment]
The more I thinking about it the more I think that I wouldn't change it:
1. Users would be confused that they can't move a folder because somewhere deep in the hierarchy is a locked file.
2. It can be quite time consuming operations to find out whether there exists a locked file or folder under a folder.
3. The principle of locking is that an item is locked if one of the parent folders is locked and not vice versa.
4. It's related not only to WebDAV but to UI too.
