### ISSUE TITLE
Workflow "New Step" dialog not appearing

### ISSUE THREAD

**Issue by mrazek** [danmunn/redmine_dmsf#730]
This error message is in production.log

Started GET "/dmsf_workflows/21/new_step" for 10.0.2.11 at 2017-06-01 09:46:20 +0200
Processing by DmsfWorkflowsController#new_step as JS
  Parameters: {"id"=>"21"}
  Current user: honza (id=3)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 3.3ms)

ActiveRecord::StatementInvalid (PG::GroupingError: ERROR:  column "dmsf_workflow_steps.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "dmsf_workflow_steps".* FROM "dmsf_workflow_steps" WH...
               ^
: SELECT "dmsf_workflow_steps".* FROM "dmsf_workflow_steps" WHERE "dmsf_workflow_steps"."dmsf_workflow_id" = $1 GROUP BY "dmsf_workflow_steps"."step"  ORDER BY step ASC,$
  plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:292:in `new_step'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

My configuration is
redmine 3.3.1.stable
Ruby 2.3.0-p0 (2015-12-25) [x86_64-linux]
Rails 4.2.7.1
DMSF 1.5.9 (downloaded ca 03/2017)
PostgreSQL 9.4.10

Please, do you have any advice?

**Comment by mrazek** [comment]
Seems that GROUP BY causes this issue. I changed line 292 in plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb

from
`@steps = @dmsf_workflow.dmsf_workflow_steps.group(:step).to_a`

to
`@steps = @dmsf_workflow.dmsf_workflow_steps.to_a`

and now the "New Step" dialog is appearing.

**Comment by picman** [comment]
That is a good quick workaround but not a solution of the problem as we need the grouping here. Otherwise there might be steps 1,2,... multiple times in the pick list. My solution looks as follows:

```ruby
-- @steps = @dmsf_workflow.dmsf_workflow_steps.group(:step).to_a
++ @steps = @dmsf_workflow.dmsf_workflow_steps.select('step, MAX(name) AS name').group(:step)
```

**Comment by mrazek** [comment]
Unfortunately, proposed solution does not work for me. So I still have to use my workaround...

**Comment by picman** [comment]
And what is the error now? The same? Could you post the production log?

**Comment by mrazek** [comment]
Hope this is it...

ActionView::Template::Error (PG::GroupingError: ERROR:  column "dmsf_workflow_steps.operator" must appear in the GROUP BY clause or be use$
LINE 1: ... "dmsf_workflow_steps"."step"  ORDER BY step ASC, operator D...
                                                             ^
: SELECT step, MAX(name) AS name FROM "dmsf_workflow_steps" WHERE "dmsf_workflow_steps"."dmsf_workflow_id" = $1 GROUP BY "dmsf_workflow_st$
    31:
    32: <fieldset class="box">
    33:   <legend><%= l(:label_dmsf_workflow_step) %></legend>
    34:   <%= select_tag 'step', dmsf_workflow_steps_options_for_select(@steps),
    35:     :id => 'selected_step', :onchange => "$('#dmsf_step_name').toggle(this.value == 0);", :style => 'max-width: 40%' %>
    36:   <span id="dmsf_step_name">&nbsp;
    37:     <%= label_tag 'name', l(:field_name) %>

**Comment by picman** [comment]
Hm, that's strange :-(

I've installed Postgres and made a few basic tests:

```sql
# select * from dmsf_workflow_steps;
 id | step | operator |   name   | dmsf_workflow_id 
----+------+----------+----------+------------------
  1 |    1 |        1 | 1st step |               12
  3 |    2 |        0 | 2nd step |               12
  2 |    1 |        0 |          |               12
(3 rows)
```
And now the original error due to the missing name column in the group by:
```sql
# SELECT step, name AS name FROM dmsf_workflow_steps where dmsf_workflow_id = 12 group by step;
ERROR:  column "dmsf_workflow_steps.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT step, name AS name FROM dmsf_workflow_steps where dms...
                     ^
```
And now a correct query with the name column wrapped into an aggregate function:
```sql
# SELECT step, max(name) AS name FROM dmsf_workflow_steps where dmsf_workflow_id = 12 group by step;
 step |   name   
------+----------
    1 | 1st step
    2 | 2nd step
(2 rows)
```
I really don't understand your case why the operator column is required in group by when is not in the select.

**Comment by picman** [comment]
Any feedback? Could you try the query in your database, please?

**Comment by mrazek** [comment]
Sorry, I am too overloaded these days, hopefully I will manage to test it during this week and provide feedback.

**Comment by davidgxxl** [comment]
Hi picman and mrazek.

I had this issue in two redmine instances.

Following the propposed workaround by picman here my workaround:
in redmine_installation/plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb

@steps = @dmsf_workflow.dmsf_workflow_steps.select('step, operator').group(:step,:operator)

I'm not sure if this can be the ultimate fix, but at least we can be able to add a new step.

Please let me know if this change was useful for you mrazek. 

picman, if you need adittional log information, let me know as well.

Thanks and regards.

**Comment by picman** [comment]
Your proposal is wrong:

1. The purpose of this query is to select list of existing steps. Why to group by operator?
2. All columns used in the group must be presented in the select too. Operator is missing in your query.

What is wrong in my query?

```ruby
@steps = @dmsf_workflow.dmsf_workflow_steps.select('step, MAX(name) AS name').group(:step)
```

**Comment by mrazek** [comment]
Unfortunatelly, i am extremely busy these days and I assume, I won't be able to help with this issue till the end of August, although I would like to help. and check it...:/ I hope, I will have some time during September for doing this.

**Comment by davidgxxl** [comment]
Hi guys.

Picman, I'm not saying your query is wrong. You are rigth in what you say.

I just thought if the issue was due to a "group" it was'nt so important add the "operator" field in group.

Here my production log when trying add new step using your query:

ActionView::Template::Error (PG::GroupingError: ERROR:  column "dmsf_workflow_steps.operator" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ... "dmsf_workflow_steps"."step"  ORDER BY step ASC, operator D...
                                                             ^
: SELECT step, MAX(name) AS name FROM "dmsf_workflow_steps" WHERE "dmsf_workflow_steps"."dmsf_workflow_id" = $1 GROUP BY "dmsf_workflow_steps"."step"  ORDER BY step ASC, operator DESC):
    31: 
    32: <fieldset class="box">
    33:   <legend><%= l(:label_dmsf_workflow_step) %></legend>
    34:   <%= select_tag 'step', dmsf_workflow_steps_options_for_select(@steps),
    35:     :id => 'selected_step', :onchange => "$('#dmsf_step_name').toggle(this.value == 0);", :style => 'max-width: 40%' %>
    36:   <span id="dmsf_step_name">&nbsp;
    37:     <%= label_tag 'name', l(:field_name) %>
  plugins/redmine_dmsf/app/helpers/dmsf_workflows_helper.rb:51:in `dmsf_workflow_steps_options_for_select'
  plugins/redmine_dmsf/app/views/dmsf_workflows/_new_step_form.html.erb:34:in `_plugins_redmine_dmsf_app_views_dmsf_workflows__new_step_form_html_erb__3387666064119035671_70178748130140'
  plugins/redmine_dmsf/app/views/dmsf_workflows/_new_step_modal.html.erb:26:in `block in _plugins_redmine_dmsf_app_views_dmsf_workflows__new_step_modal_html_erb__1519290326653140772_41244060'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  plugins/redmine_dmsf/app/views/dmsf_workflows/_new_step_modal.html.erb:25:in `_plugins_redmine_dmsf_app_views_dmsf_workflows__new_step_modal_html_erb__1519290326653140772_41244060'
  plugins/redmine_dmsf/app/views/dmsf_workflows/new_step.js.erb:22:in `_plugins_redmine_dmsf_app_views_dmsf_workflows_new_step_js_erb__489709948870782143_70178747957540'
  plugins/redmine_dmsf/app/controllers/dmsf_workflows_controller.rb:294:in `new_step'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


My enviroment:

Ubuntu 16.04 Server
(PostgreSQL) 9.5.7
Redmine 3.3.2
DMSF Plugin at April 10 Master Branch Version

**Comment by picman** [comment]
Okay, you're right. Let's add the operator column into the grouping.

**Comment by davidgxxl** [comment]
Hi picman. 

Great!

I tested this "fix" in another redmine instance with this config:
Ubuntu Server 16.04
Postgresql 9.5.7
Redmine 3.4.2
and DMSF at August 03 Master Branch Version

and works well too.

If there any other related issue with this I'll let you know.

Thanks.

**Comment by ex-troll** [comment]
Hi.
This patch works well.
If you do a backport it in 1.5.9, it will be great.
TY

**Comment by picman** [comment]
Done.
