### ISSUE TITLE
Microsoft's acquisition of GitHub

### ISSUE THREAD

**Issue by picman** [danmunn/redmine_dmsf#871]
After Microsoft's acquisition of GitHub I wonder whether not to migrate DMSF project to another portal. [GitLab](https://gitlab.com/) or [Bitbucket](https://bitbucket.org/) come to my mind. What DMSF community thinks about that? Are there any reason why not doing that? Please comment.

**Comment by mrazek** [comment]
I don't expect any critical changes soon, however.... GitLab works fine AFAIK, our developers use it laready 3 years for sofware projects.

**Comment by M0d3rn15t** [comment]
I am not sure what your immediate concerns are.

I wouldn't expect anything to negative to happen for at least a year.

**Comment by flybyray** [comment]
If alternatives have a mirror option, it would not be wrong to create (reserve) projects there.
If quick precautions should become necessary, one has withdrawal options.
The biggest fears must have private or commercial customers of Github, who use the special features of Github.
Some customers also have long-term contracts with Github. It would be interesting to know whether they have been given special termination rights or special termination rights due to the takeover.
That would be an indication that we should be even more concerned.
Source code is the link between man and machine. Artificial intelligence in the evaluation and processing of source code should not be underestimated. It is precisely in this area that I see the greatest danger in the takeover.
One could also see here the goodwill, but we all know to big companies are evil.
