### ISSUE TITLE
Upgrading Ubuntu Xenial to Bionic messed up installation...

### ISSUE THREAD

**Issue by Brigithubert** [danmunn/redmine_dmsf#944]
Hello,

after upgrading my server from Xenial to Bionic (no full backup done...) the Redmine installation is messed up: Obviously, Redmine 3.3.1 does not work with ruby 2.5.

So I thought it was a good idea to upgrade to Redmine 4.0.0 -- it wasn't as DMSF (master) is currently not supporting it (see #931).

Eventually, I "upgraded" to Redmine 3.4.7, purged ruby2.5 with apt and installed ruby2.4 with rvm. This generally works now, but DMSF cannot find any documents any more. They are physically there, but it seems the database paths differ. Next try was to upgrade DMSF from 1.5.8 to 1.6.2 (master). When running `bundle exec rake redmine:plugins:migrate RAILS_ENV=production` I get 

> DmsfFileRevisions ID 1: Origin '/opt/redmine-3.3.1/files/dmsf/<...> doesn't exist

However, the origin should be "/opt/redmine-3.4.7/files/<...>" as I copied them over. Can I change this manually?

Alternatively, can I run some kind of a bash script to import all files back into DMSF (i.e. match them with the database entries)?

Any help to recover my system is highly appreciated!

Thanks
Nik

**Comment by picman** [comment]
During the upgrade the plugin wants to relocate documents on the disk from dmsf/p_identifier to dmsf/2019/01,.... The files on the disk are no more organized by project identifier but by dates. The problem in your case is that you change the path to the plugin during the upgrade. The migration expects that the root path to the files remains unchanged.
You probably use absolute paths in the plugin's setting instead of relative ones. Try to change the absolute path to a relative one, e.g.: _files/dmsf_ instead of _/opt/redmine-3.3.1/files/dmsf_ and then start the migration.
There is also a script for manual migration mentioned here: #767

**Comment by Brigithubert** [comment]
Thank you for that hint! I was eventually able to migrate and now it works again.
